// Prints the app's schema as Postgres DDL (what ensureSchema() would create), so it can be
// pasted into the Supabase SQL editor by anyone who would rather create the tables by hand.
//   npx tsx scripts/dump-schema.ts > docs/supabase-schema.sql
import { toPostgres } from "../src/lib/pgClient";
import fs from "fs";
import path from "path";

const db = fs.readFileSync(path.join(__dirname, "..", "src", "lib", "db.ts"), "utf-8");
const mem = fs.readFileSync(path.join(__dirname, "..", "src", "lib", "memory.ts"), "utf-8");
const out: string[] = [
  "-- The Job Search Agent's schema, as Postgres DDL.",
  "-- Generated by scripts/dump-schema.ts from src/lib/db.ts and src/lib/memory.ts.",
  "-- You do NOT need to run this: the app creates these tables on its first request.",
  "",
];
for (const src of [db, mem]) {
  for (const m of src.matchAll(/CREATE TABLE IF NOT EXISTS[\s\S]*?\);/g)) out.push(toPostgres(m[0]), "");
}
for (const m of db.matchAll(/"(ALTER TABLE [^"]+)"/g)) out.push(`${toPostgres(m[1])};`);
console.log(out.join("\n"));
