-- The Job Search Agent's schema, as Postgres DDL.
-- Generated by scripts/dump-schema.ts from src/lib/db.ts and src/lib/memory.ts.
-- You do NOT need to run this: the app creates these tables on its first request.

CREATE TABLE IF NOT EXISTS profiles (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      resume_text TEXT NOT NULL,
      preferences_text TEXT NOT NULL,
      is_active INTEGER NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL DEFAULT (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
      updated_at TEXT NOT NULL DEFAULT (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
    );

CREATE TABLE IF NOT EXISTS jobs (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      raw_text TEXT NOT NULL,
      source_url TEXT,
      created_at TEXT NOT NULL DEFAULT (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
    );

CREATE TABLE IF NOT EXISTS evaluations (
      job_id TEXT PRIMARY KEY,
      stage TEXT NOT NULL,
      fit_score REAL,
      matched_skills TEXT,
      missing_skills TEXT,
      fit_rationale TEXT,
      hard_constraint_violations TEXT,
      injection_detected INTEGER NOT NULL DEFAULT 0,
      injection_snippets TEXT,
      approval_note TEXT,
      draft TEXT,
      profile_id TEXT,
      profile_name TEXT,
      resume_snapshot TEXT,
      trace_json TEXT NOT NULL,
      state_json TEXT NOT NULL,
      updated_at TEXT NOT NULL DEFAULT (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
      FOREIGN KEY (job_id) REFERENCES jobs(id)
    );

CREATE TABLE IF NOT EXISTS harness_settings (
      profile_id TEXT NOT NULL,
      key        TEXT NOT NULL,
      value      TEXT NOT NULL,
      updated_at TEXT NOT NULL DEFAULT (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
      PRIMARY KEY (profile_id, key)
    );

CREATE TABLE IF NOT EXISTS workspace_state (
      workspace_id      TEXT PRIMARY KEY,
      active_profile_id TEXT,
      created_at        TEXT NOT NULL DEFAULT (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
      updated_at        TEXT NOT NULL DEFAULT (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
    );

CREATE TABLE IF NOT EXISTS requirement_ledgers (
      job_hash   TEXT PRIMARY KEY,
      ledger_json TEXT NOT NULL,
      source     TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
    );

CREATE TABLE IF NOT EXISTS fit_cache (
      job_hash   TEXT NOT NULL,
      fit_key    TEXT NOT NULL,
      fit_json   TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')),
      PRIMARY KEY (job_hash, fit_key)
    );

CREATE TABLE IF NOT EXISTS eval_history (
      job_hash     TEXT NOT NULL,
      workspace_id TEXT,
      profile_id   TEXT,
      profile_name TEXT,
      score        REAL,
      stage        TEXT,
      at           TEXT NOT NULL DEFAULT (to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'))
    );

ALTER TABLE evaluations ADD COLUMN cover_letter TEXT;
ALTER TABLE evaluations ADD COLUMN tailored_resume TEXT;
ALTER TABLE profiles ADD COLUMN workspace_id TEXT;
ALTER TABLE jobs ADD COLUMN workspace_id TEXT;
ALTER TABLE jobs ADD COLUMN content_hash TEXT;
ALTER TABLE evaluations ADD COLUMN workspace_id TEXT;
